package clases;
// Generated 26/12/2013 09:26:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * InventHistorial generated by hbm2java
 */
public class InventHistorial  implements java.io.Serializable {


     private Integer identificador;
     private InventProducto inventProducto;
     private Date fecha;
     private int cantidad;

    public InventHistorial() {
    }

    public InventHistorial(InventProducto inventProducto, Date fecha, int cantidad) {
       this.inventProducto = inventProducto;
       this.fecha = fecha;
       this.cantidad = cantidad;
    }
   
    public Integer getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(Integer identificador) {
        this.identificador = identificador;
    }
    public InventProducto getInventProducto() {
        return this.inventProducto;
    }
    
    public void setInventProducto(InventProducto inventProducto) {
        this.inventProducto = inventProducto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


