package clases;
// Generated 26/12/2013 09:26:29 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * InventProducto generated by hbm2java
 */
public class InventProducto  implements java.io.Serializable {


     private Integer identificador;
     private String nombre;
     private String descripcion;
     private String unidadDeMedida;
     private String tipo;
     private String imagen;
     private Set<InventHistorial> inventHistorials = new HashSet<InventHistorial>(0);

    public InventProducto() {
    }

	
    public InventProducto(String nombre, String descripcion, String unidadDeMedida, String tipo) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.unidadDeMedida = unidadDeMedida;
        this.tipo = tipo;
    }
    public InventProducto(String nombre, String descripcion, String unidadDeMedida, String tipo, String imagen, Set<InventHistorial> inventHistorials) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.unidadDeMedida = unidadDeMedida;
       this.tipo = tipo;
       this.imagen = imagen;
       this.inventHistorials = inventHistorials;
    }
   
    public Integer getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(Integer identificador) {
        this.identificador = identificador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUnidadDeMedida() {
        return this.unidadDeMedida;
    }
    
    public void setUnidadDeMedida(String unidadDeMedida) {
        this.unidadDeMedida = unidadDeMedida;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set<InventHistorial> getInventHistorials() {
        return this.inventHistorials;
    }
    
    public void setInventHistorials(Set<InventHistorial> inventHistorials) {
        this.inventHistorials = inventHistorials;
    }




}


